name: Go

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tg: ${{ steps.filter.outputs.tg }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Test
      run: go test ./...

    - name: Build
      run: go build -v ./...
       
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Echo tag
      run: |- 
        echo ${{ steps.tag_version.outputs.new_tag }}

    - name: Build the Docker image
      run: |- 
        docker build . --file Dockerfile --tag mehabhalodiya/color-demo:${{ github.sha }}

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'mehabhalodiya/color-demo:${{ github.sha }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL'
      
    - name: Docker Push
      run: |-
        # docker push mehabhalodiya/color-demo:${{ github.sha }}
